# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '9.6.0'
    puppet_agent:
      repo: 'puppetlabs/puppet_agent'
      ref: '4.21.0'
    inifile:
      repo: 'puppetlabs/inifile'
      ref: '6.1.1'
    facts:
      repo: 'puppetlabs/facts'
      ref: '1.6.0'
    reboot:
      repo: 'puppetlabs/reboot'
      ref: '5.0.0'
    pwshlib:
      repo: 'puppetlabs/pwshlib'
      ref: '1.2.2'
    powershell:
      repo: 'puppetlabs/powershell'
      ref: '6.0.0'
    scheduled_task:
      repo: 'puppetlabs/scheduled_task'
      ref: '1.0.1'
    apt:
      repo: 'puppetlabs/apt'
      ref: '9.4.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '9.0.2'
    yum:
      repo: 'puppet/yum'
      ref: '7.1.0'
  repositories:
    patching_as_code:
      repo: 'https://github.com/garrettrowell/puppetlabs-patching_as_code.git'
      branch: 'modify'
    pe_patch:
      repo: 'https://github.com/puppetlabs/pe_patch.git'
      branch: 'main'
    cron_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-cron_core.git'
      ref: 'v1.3.0'
